image: ubuntu:20.04

build:
  stage: build
  script:
    - apt update
    - apt install android-tools-mkbootimg bc build-essential ca-certificates cpio curl git kmod libssl-dev libtinfo5 python2 sudo unzip wget xz-utils -y --no-install-recommends
    - ln -sf python2.7 /usr/bin/python
    - ./build.sh
  artifacts:
    paths:
      - out/*

twrp-flashable:
  stage: build
  variables:
    RAWIMG: "1"
  script:
    - apt update
    - apt install -y img2simg jq sudo wget xz-utils
    - ./build/fetch-and-prepare-latest-ota.sh "16.04/arm64/android9/devel" "jasmine_sprout" ota
    - mkdir -p out
    - ./build/system-image-from-ota.sh ota/ubuntu_command out
  artifacts:
    paths:
      - out/boot.img
      - out/system.img

flashable:
  stage: build
  variables:
    RAWIMG: "0"
  script:
    - apt update
    - apt install -y img2simg jq sudo wget xz-utils
    - ./build/fetch-and-prepare-latest-ota.sh "16.04/arm64/android9/devel" "jasmine_sprout" ota
    - mkdir -p out
    - ./build/system-image-from-ota.sh ota/ubuntu_command out
  artifacts:
    paths:
      - out/boot.img
      - out/system.img
